version: '0.0'

services:
  db:
    image: mariadb
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 3
    environment:
      MARIADB_ROOT_PASSWORD: toor
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
    command: ls /usr/local/bin
      # - type: tmpfs
      #   target: /docker-entrypoint-initdb.d

  # adminer:
  #   image: adminer
  #   restart: on-failure
  #   ports:
  #     - 10000:8080
  
  # blog-service:
  #   build: .
  #   ports:
  #     - 8000:8000
  #   depends_on:
  #     db:
  #       condition: service_completed_successfully
# tmpfs: ./sql