# version: "0.0"

services:
  db:
    image: mariadb
    # deploy:
    #   restart_policy:
    #     condition: on-failure
    #     max_attempts: 3
    environment:
      MARIADB_ROOT_PASSWORD: toor
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
      # - type: tmpfs
      #   target: /docker-entrypoint-initdb.d
    ports:
      - 3306

  adminer:
    image: adminer
    restart: on-failure
    ports:
      - 10000:8080
    depends_on:
      - db 

  # blog-service:
  #   build: .
  #   ports:
  #     - 8000:8000
  #   depends_on:
  #     - db
# tmpfs: ./sql

# endpoints:
#   db:
#     - path: /
#       service: db
#       port: 3306