# version: "0.0"

services:
  db:
    image: mariadb
    # deploy:
    #   restart_policy:
    #     condition: on-failure
    #     max_attempts: 3
    environment:
      - MARIADB_USER=mysql
      - MARIADB_PASSWORD=elon
      - MARIADB_ROOT_PASSWORD=toor
      - MYSQL_INITDB_SKIP_TZINFO=yes
      
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
      # - type: tmpfs
      #   target: /docker-entrypoint-initdb.d
    ports:
      - 3306

  adminer:
    image: adminer
    restart: on-failure
    ports:
      - 10000:8080
    depends_on:
      - db 
  tracing:
    image: jaegertracing/all-in-one
    environment:
      - COLLECTOR_ZIPKIN_HOST_PORT=:9411
      - COLLECTOR_OTLP_ENABLED=true 
    ports:
      - 6831:6831/udp 
      - 6832:6832/udp 
      - 5778:5778 
      - 16686:16686 
      - 4317:4317 
      - 4318:4318 
      - 14250:14250 
      - 14268:14268 
      - 14269:14269 
      - 9411:9411
  # blog-service:
  #   build: .
  #   ports:
  #     - 8000:8000
  #   depends_on:
  #     - db
# tmpfs: ./sql

# endpoints:
#   db:
#     - path: /
#       service: db
#       port: 3306