version: '0.0'

services:
  db:
    image: mariadb
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: toor
    volumes:
      - ./sql: /docker-entrypoint-initdb.d

  adminer:
    image: adminer
    restart: always
    ports:
      - 10000:8080
  
  blog-service:
    build: .
    ports:
      - 8000:8000
    