Server:
  RunMode: debug
  HttpPort: 8000
  ReadTimeout: 60
  WriteTimeout: 60

App:
  LogPath: storage/logs
  LogFileName: app
  LogFileExt: .log
  DefaultPageSize: 10
  MaxPageSize: 100

Database:
  DBType: mariadb
  Username: root
  Password: toor
  # Host: db:3306
  Host: 127.0.0.1:49154
  DBName: blog
  TablePrefix: blog_
  Charset: utf8
  ParseTime: True
  MaxIdleConns: 10
  MaxIdOpenConns: 30
