// Copyright 2020 Lingfei Kong <colin404@foxmail.com>. All rights reserved.
// Use of this source code is governed by a MIT style
// license that can be found in the LICENSE file.

// Code generated by "codegen -type=int"; DO NOT EDIT.

package errcode

// init register error codes defines in this source code to `github.com/marmotedu/errors`
func init() {
	register(ErrArticleNotFound, 400, "Article not found")
	register(ErrArticleAlreadyExist, 400, "Article already exists")
	register(ErrArticleTagNotFound, 400, "ArticleTag not found")
	register(ErrArticleTagAlreadyExist, 400, "ArticleTag already exists")
	register(ErrAuthNotFound, 400, "Auth not found")
	register(ErrAuthAlreadyExist, 400, "Auth already exists")
	register(Success, 200, "OK")
	register(ServerError, 500, "Internal error")
	register(InvalidParams, 400, "Parameters error")
	register(TooManyRequests, 400, "Too many requests")
	register(UnauthorizedAuthNotExist, 400, "Authorization failed: can't find AppKey and AppSecret")
	register(UnauthorizedTokenError, 400, "Authorization failed: token error")
	register(UnauthorizedTokenTimeout, 400, "Authorization failed: token timeout")
	register(UnauthorizedTokenGenerate, 400, "Authorization failed: failed generating a token")
	register(ErrTagNotFound, 400, "Tag not found")
	register(ErrTagAlreadyExist, 400, "Tag already exists")
	register(ErrUploadFile, 400, "Failed uploading files")
}
