basePath: /api/v1
definitions:
  errcode.Error:
    type: object
  model.Tag:
    properties:
      created_by:
        type: string
      created_on:
        type: integer
      deleted_on:
        type: integer
      id:
        type: integer
      is_del:
        type: integer
      modified_by:
        type: string
      modified_on:
        type: integer
      name:
        type: string
      state:
        type: integer
    type: object
host: https://blog-service-elchn.cloud.okteto.net
info:
  contact:
    name: Elchn
  description: This is a simple blog service based on golang,mariadb and okteto
  title: blog service
  version: v0.0
paths: {}
swagger: "2.0"
