basePath: /api/v1
definitions:
  errcode.Error:
    type: object
  model.Tag:
    properties:
      created_at:
        type: integer
      created_by:
        type: string
      deleted_at:
        type: integer
      id:
        type: integer
      is_del:
        type: integer
      modified_at:
        type: integer
      modified_by:
        type: string
      name:
        type: string
      state:
        type: integer
    type: object
host: https://blog-service-poiyyort.cloud.okteto.net
info:
  contact:
    name: Elchn
  description: This is a simple blog service based on golang,mariadb and okteto
  title: blog service
  version: v0.0
paths:
  /api/v1/tags:
    get:
      parameters:
      - description: tag name
        in: query
        maxLength: 100
        name: name
        type: string
      - default: 1
        description: state
        in: query
        name: state
        type: integer
      - description: page index
        in: query
        name: page
        type: integer
      - description: size per page
        in: query
        name: page_size
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: succeeded
          schema:
            $ref: '#/definitions/model.Tag'
        "400":
          description: request errors
          schema:
            $ref: '#/definitions/errcode.Error'
        "500":
          description: internal errors
          schema:
            $ref: '#/definitions/errcode.Error'
      summary: get a list of tags
swagger: "2.0"
